### PR TITLE
fix scanpy version

### PR DESCRIPTION
**Pull request by SarahOuologuem**

### CODE REVIEW

**Comment by bio-la** [comment]
https://github.com/scverse/muon/issues/135

**Comment by SarahOuologuem** [comment]
@bio-la Unpinning the scanpy and scipy versions doesn't work for the spatial workflows, e.g. see [here]( https://github.com/DendrouLab/panpipes/actions/runs/8719259491/job/23918240600?pr=251#step:9:76)
Scipy version 1.13.0 throws errors in the spatial workflows. The workflows work with a pinned version of scipy to 1.12.0 instead of 1.13.0. Or should i rather pin scipy eg to < 1.13.0?

**Comment by bio-la** [comment]
Ok let's roll with it for now. My guess is all of those pins for scvi and Jax are the issues but let's keep a working env for spatial and I'll take a look at versions later! Should I add my review and merge now?

**Comment by SarahOuologuem** [comment]
okay, thank you! yes, i would say so

**Review by bio-la — APPROVED** [review]

**Review by bio-la — APPROVED** [review]

**Pull request merged**
