### PR TITLE
First draft of GitHub Actions

### PR DESCRIPTION
**Pull request by kevinrue**

### CODE REVIEW

**Review by bio-la — COMMENTED** [review]
this looks good to me, 
how is the action triggered in response to for example modifications to the ingestion tutorial yml ?

**Comment by kevinrue** [comment]
Any commit pushed to the main branch or in a pull request to the main branch runs this action.

**Comment by bio-la** [comment]
the question is actually the other way around. any changes here (https://github.com/DendrouLab/panpipes) trigger the action. 
but will changes in https://github.com/DendrouLab/panpipes-tutorials trigger the action here (on https://github.com/DendrouLab/panpipes) ?
i don't think so, am i missing something?

**Comment by bio-la** [comment]
ok thanks for clarifying!
i think we can safely merge and this action will be the first check for this PR https://github.com/DendrouLab/panpipes/pull/158,
if something went wrong in panpipes ingest make config we should know (since @Lilly-May is modifying the pipeline.yml, this is the only part of the action that is affected by that PR)

**Review by bio-la — APPROVED** [review]

**Comment by kevinrue** [comment]
Goes without saying but updating the input files on figshare also wouldn't trigger the action.

**Pull request merged**
