### PR TITLE
renamed /python/run_scanpyQC_REP.py & commented out barcode_mtd args …

### PR DESCRIPTION
**Pull request by deevdevil88**
made changes to deal with #2 and also made changes to `panpipes_qc_mm.py` for `bg_concat` and commented out barcode_mtd related args.

Best,
Devika

### CODE REVIEW

**Comment by deevdevil88** [comment]
also we updated `make_adata_from_csv.py` to make update the `prot` modality to not have the `hashing_ab` info, so that that making adtaa objects doesnt error.

**Comment by deevdevil88** [comment]
While trying to change the defaults for scvi model_args  for RNA in `panpipes_integration.py`, noticed that the `pipeline.yml` had the args 'n_latent' and 'n_layers' as they should be called based on https://docs.scvi-tools.org/en/0.20.1/api/reference/scvi.model.SCVI.html  written as 'nlatent' and 'nlayers'. This was causing the pipeline to error, as model_args are called as is in the `[batch_correct_scvi].py(https://github.com/DendrouLab/panpipes/blob/main/python/batch_correct_scvi.py#:~:text=scvi_model_args%20%3D%20%20%7Bk%3A%20v%20for%20k%2C%20v%20in%20params%5B%27rna%27%5D%5B%27scvi%27%5D%5B%27model_args%27%5D.items()%20if%20v%20is%20not%20None%7D)` script

**Comment by deevdevil88** [comment]
Added harmony  `sigma` and `harmony_pcs` model_args to ruffus in pipeline_integration.py for `rna` and `prot` and `atact` modalities, and also changed `neighbors_n_pcs` to `neighbors_ndims` in all places for harmony to clarify between harmony pcs and neighbor dims.

**Comment by deevdevil88** [comment]
After making changes to `batch_correct_harmony.py` for `neighbours_npcs` to `neighbours_ndims`, had to change `npcs` to `ndims` in `batch_correct_wnn.py` for when using  harmony neighbours for the modailities.  see screenshot of error 
Screenshot 2023-02-23 at 18 16 30

**Comment by deevdevil88** [comment]
as `neighbours_n_pcs` is a `PARAM` for all methods, this has been reverted back to its original and only harmony_npcs has been added.

**Comment by deevdevil88** [comment]
parameterised 'sigma' paramter for batch correction with Harmony.

**Review by crichgriffin — COMMENTED** [review]
All good, I will merge with the master

**Review by crichgriffin — APPROVED** [review]
Approved

**Pull request merged**
