### PR TITLE
Fc installation

### PR DESCRIPTION
**Pull request by bio-la**
changed and tested installation scripts
it works on macos 11.3.

@crichgriffin let's discuss additional ST dependencies and how to add conda dependencies in the install.py script!

### CODE REVIEW

**Comment by crichgriffin** [comment]
Can you remove the .history folder from the commit and add it to the .gitignore?

**Comment by bio-la** [comment]
pipeline still complains about bbknn and requires to `pip install bbknn`. can you check the installation script and include this? @crichgriffin

**Comment by crichgriffin** [comment]
It is in the installation script :/

**Comment by bio-la** [comment]
Hey @crichgriffin do we still have something pending here or can we merge?
bbknn installation is sorted out now with the [new update](https://github.com/Teichlab/bbknn/issues/54) 
thanks!

**Pull request merged**
